DROP TABLE IF EXISTS TREATMENTPLAN;

CREATE TABLE TREATMENTPLAN (
  id BIGINT AUTO_INCREMENT  PRIMARY KEY,
  ACTION VARCHAR(255) NOT NULL,
  SUBJECT_PATIENT VARCHAR(255) NOT NULL,
  START_TIME TIMESTAMP NOT NULL,
  END_TIME TIMESTAMP NOT NULL,
  RECURRENCE_PATTERN VARCHAR(255) NOT NULL
);
