DROP TABLE IF EXISTS TREATMENT_PLAN;

CREATE TABLE TREATMENT_PLAN (
  id BIGINT AUTO_INCREMENT  PRIMARY KEY,
  ACTION VARCHAR(255) NOT NULL,
  SUBJECT_PATIENT VARCHAR(255) NOT NULL,
  START_TIME TIMESTAMP NOT NULL,
  END_TIME TIMESTAMP NOT NULL,
  RECURRENCE_PATTERN VARCHAR(255) NOT NULL
);


DROP TABLE IF EXISTS TREATMENT_TASK;

CREATE TABLE TREATMENT_TASK (
  id BIGINT AUTO_INCREMENT  PRIMARY KEY,
  ACTION VARCHAR(255) NOT NULL,
  SUBJECT_PATIENT VARCHAR(255) NOT NULL,
  START_TIME TIMESTAMP NOT NULL,
  IS_ACTIVE BOOLEAN NOT NULL
);

